run_name: basic_factors

preprocessing:
  - name: remove_non_functional
    cutoff: -0.508
  - name: subsample
    fraction: 0.1
  - name: remove_non_significant
    cutoff: 0.05
  - name: extend_mutated_sequence
    wildtype_start_position: 593
    length: 117

factors:
  - name: mutated_amino_acids

  - name: neural_network
    splitting_config:
      train_fraction: 0.6
      test_fraction: 0.2
      group_variable: mutated_amino_acids

    dataset_config:
      variables:
        - fitness
      target_variable: fitness

    dataloader_config:
      batch_size: 32
      shuffle: true
    
    optimizer_config:
      name: adam
    
    loss_config:
      name: mse

    model_config:
      name: prediction_cnn

    trainer_config:
      max_epochs: 100
      
analysis:
  - name: correlation_with_fitness
    variables:
      - prediction
    group_by:
      - mutated_amino_acids
    significant_threshold: 0.05