run_name: test_rbs_rates

preprocessing:
  - name: remove_non_functional
    cutoff: -0.508
  # - name: subsample
  #   fraction: 0.01
  - name: extend_mutated_sequence
    wildtype_start_position: 593
    length: 117
  - name: rna_loops
    column: mutated_wildtype_dna

factors:
  - name: mutated_amino_acids
  - name: minimum_free_energy
  - name: non_wildtype_rbs_rate
  - name: rbs_rates

analysis:
  - name: correlation_with_fitness
    variables:
      - non_wildtype_rbs_rate
      - minimum_free_energy
      - rbs_expression_25
      - rbs_expression_38
      - rbs_expression_70
      - rbs_expression_82
      - rbs_expression_87
      - rbs_expression_99
      - rbs_expression_100
      - rbs_expression_101
      - rbs_expression_102
      - rbs_expression_103
      - rbs_expression_104
      - rbs_expression_105
      - rbs_expression_106
      - rbs_expression_107
    group_by:
      - mutated_amino_acids
    significant_threshold: 0.05
  