run_name: basic_cnn_synonymous_batches

preprocessing:
  - name: remove_non_functional
    cutoff: -0.508
  # - name: subsample
  #   fraction: 0.01
  - name: extend_mutated_sequence
    wildtype_start_position: 593
    length: 117
  - name: rna_loops
    column: mutated_wildtype_dna

factors:
  - name: mutated_amino_acids
  - name: neural_network
    project_name: basic_cnn_synonymous_batches

    splitting_config:
      train_fraction: 0.6
      test_fraction: 0.2
      group_variable: mutated_amino_acids

    dataset_config:
      variables:
        - rna_loops
        - mutated_amino_acids
      target_variable: fitness

    dataloader_config:
      batch_size: 16
      shuffle: true
    
    optimizer_config:
      name: adam
    
    loss_config:
      name: mse

    model_config:
      name: prediction_cnn
      input_size: 117
      embedding_size: 64
      num_conv_layers: 7
      num_conv_filters: 64
      filter_size: 5
      fully_connected_size: 64

    trainer_config:
      max_epochs: 50

analysis:
  - name: correlation_with_fitness
    variables:
      - prediction
    group_by:
      - mutated_amino_acids
    significant_threshold: 0.05