run_name: cnn_vae

preprocessing:
  - name: remove_non_functional
    cutoff: -0.508
  # - name: subsample
  #   fraction: 0.1
  - name: extend_mutated_sequence
    wildtype_start_position: 593
    length: 117
  - name: rna_loops
    column: mutated_wildtype_dna

factors:
  - name: mutated_amino_acids
  - name: minimum_free_energy
  - name: neural_network
    project_name: cnn_vae

    splitting_config:
      train_fraction: 0.6
      test_fraction: 0.2
      group_variable: mutated_amino_acids

    dataset_config:
      variables:
        - rna_loops
      target_variable: fitness

    dataloader_config:
      batch_size: 256
      shuffle: true
    
    optimizer_config:
      name: adam
    
    loss_config:
      name: mse

    model_config:
      name: cnn_vae
      input_size: 117
      embedding_size: 32
      num_conv_layers: 3
      num_conv_filters: 32
      filter_size: 5
      fully_connected_size: 32
      latent_size: 5
      kld_weight: 0.1

    trainer_config:
      max_epochs: 100

analysis:
  - name: correlation_with_fitness
    variables:
      - prediction_0
      - prediction_1
      - prediction_2
      - prediction_3
      - prediction_4
      - minimum_free_energy
    group_by:
      - mutated_amino_acids
    significant_threshold: 0.05
  - name: random_forest_permutation_importance
    variables:
      - minimum_free_energy
      - mutated_amino_acids
      - prediction_0
      - prediction_1
      - prediction_2
      - prediction_3
      - prediction_4
