run_name: replication_test

preprocessing:
  - name: subsample
    fraction: 0.1
  - name: remove_non_functional
    cutoff: -0.508
  - name: remove_non_significant
    cutoff: 0.05
  - name: extend_mutated_sequence
    wildtype_start_position: 593
    length: 117

factors:
  - name: mutated_amino_acids
  - name: minimum_free_energy

analysis:
  - name: correlation
    variables:
      - minimum_free_energy
    group_by:
      - mutated_amino_acids
    significant_threshold: 0.05
  